# Main metainfo
log_save_dir: './drive/MyDrive/skoltech/train_suite_ttsr_orig'

model_checkpoint_callback__monitor: ['a_psnr', 'a_ssim']
model_checkpoint_callback__save_top_k: 55
model_checkpoint_callback__mode: 'max'
model_checkpoint: './drive/MyDrive/skoltech/train_suite_ttsr_orig/version_2/checkpoints/epoch=27-a_psnr=25.1985-a_ssim=0.7553.ckpt'
composer: FullTTSRLitComposer

trainer__kwargs:
  max_epochs: 20
  accelerator: 'dp'

# Model
model: 'TTSR'
model__kwargs:
  n_feats: 64
  num_res_blocks: 16+16+8+4
  res_scale: 1.

# Training
batch_size: 9
loss: 'rec+0.01*per+0.01*tper+0.001*adv'

optimizer: Adam
lr:
  MainNet: !!float 1e-4
  LTE: !!float 1e-5
optimizer__kwargs: 
  betas: [0.9, 0.999]
  eps: !!float 1e-8

lr_scheduler: StepLR
lr_scheduler__kwargs:
  step_size: 999999
  gamma: .5

add_vgg19: True
use_discriminator: True
discriminator: Discriminator
discriminator__args: [160]

discriminator__optimizer: Adam
discriminator__lr: !!float 1e-4
discriminator__optimizer__kwargs:
  betas: [0., 0.9]
  eps: !!float 1e-8

discriminator__lr_scheduler: null
# discriminator__frequency: 2

# Datasets
train_dataset: 'CufedTrainDataset'
train_num_workers: 4
train_dataset__kwargs:
  dataset_dirpath: './CUFED/train'

val_dataset: 'CufedTestDataset'
val_num_workers: 2
val_dataset__kwargs:
  dataset_dirpath: './CUFED/test'
