# Main metainfo
log_save_dir: './logs_ttsr_cufed5'

model_checkpoint: null
model_checkpoint_callback__monitor: ['avg_val_psnr', 'avg_val_ssim']
model_checkpoint_callback__save_top_k: 5
model_checkpoint_callback__mode: 'max'
composer: TTSRLitComposer

trainer__kwargs:
  max_epochs: 2
  # track_grad_norm: 2
  # gradient_clip_val: .5
  # precision: 16
  accelerator: 'dp'
  # fast_dev_run: True

# Model
model: 'TTSR'
model__kwargs:
  n_feats: 64
  num_res_blocks: 16+16+8+4
  res_scale: 1.

# Training
batch_size: 9
loss: 'rec'

optimizer: Adam
lr:
  MainNet: !!float 1e-4
  LTE: !!float 1e-5
optimizer__kwargs: 
  betas: [0.9, 0.999]
  eps: !!float 1e-8

lr_scheduler: StepLR
lr_scheduler__kwargs:
  step_size: 999999
  gamma: .5

# Datasets
train_dataset: 'CufedTrainDataset'
train_num_workers: 4
train_dataset__kwargs:
  dataset_dirpath: '/trinity/home/l.kulikov/data/cufed/train'

val_dataset: 'CufedTestDataset'
val_num_workers: 2
val_dataset__kwargs:
  dataset_dirpath: '/trinity/home/l.kulikov/data/cufed/test'
