# Main metainfo
log_save_dir: './drive/MyDrive/skoltech/exp_3_1/lightning_logs'

model_checkpoint_callback__monitor: ['a_psnr', 'a_ssim']
model_checkpoint_callback__save_top_k: 55
model_checkpoint_callback__mode: 'max'
# model_checkpoint: './drive/MyDrive/skoltech/train_suite_ttsr_orig'
composer: FullTTSRLitComposer

trainer__kwargs:
  max_epochs: 48 #20 # 26 # 34  # 41 48
  # track_grad_norm: 2
  # gradient_clip_val: .5
  # precision: 16
  accelerator: 'dp'
  # limit_train_batches: 0.01
  # limit_val_batches: 0.1
  # fast_dev_run: True

# Model
model: 'TTSR'
model__kwargs:
  n_feats: 64
  num_res_blocks: 8+8+4+2
  res_scale: 1.

# Training
batch_size: 9
loss: 'rec+0.01*per+0.01*tper+0.001*adv'

optimizer: Adam
lr:
  MainNet: !!float 1e-4
  LTE: !!float 1e-5
optimizer__kwargs: 
  betas: [0.9, 0.999]
  eps: !!float 1e-8

lr_scheduler: StepLR
lr_scheduler__kwargs:
  step_size: 999999
  gamma: .5

add_vgg19: True
use_discriminator: True
discriminator: Discriminator
discriminator__args: [160]

discriminator__optimizer: Adam
discriminator__lr: !!float 1e-4
discriminator__optimizer__kwargs:
  betas: [0., 0.9]
  eps: !!float 1e-8

discriminator__lr_scheduler: null
# discriminator__frequency: 2

# Datasets
train_dataset: 'CufedTrainDataset'
train_num_workers: 4
train_dataset__kwargs:
  dataset_dirpath: './CUFED/train'

val_dataset: 'CufedTestDataset'
val_num_workers: 2
val_dataset__kwargs:
  dataset_dirpath: './CUFED/test'
